//
//  History.swift
//  VaultClip
//
//  Copyright (C) 2019 Matthew Davidson
//  Copyright (C) 2026 Aleksey Karakuts <aleksey@karakuts.com>
//
//  SPDX-License-Identifier: GPL-3.0-or-later
//
import Foundation
import Cocoa
import RxSwift
import RxRelay

/// Representation of all the history
class History {
    
    private var _items = [HistoryItem]()
    
    private var _lastRecordedChangeCount = BehaviorRelay<Int>(value: -1)
    
    var observableLastRecordedChangeCount: Observable<Int> {
        return _lastRecordedChangeCount.asObservable()
    }
    
    var lastRecordedChangeCount: Int {
        return _lastRecordedChangeCount.value
    }
    
    var historyFM: HistoryFileManager
    var cache: HistoryCache
    
    private var _maxItems: BehaviorRelay<Int>
    
    private final class Subscription {
        let handler: SubscribeHandler
        init(handler: @escaping SubscribeHandler) { self.handler = handler }
    }
    
    var items: [HistoryItem] {
        get { self._items }
    }
    
    var favoriteItems: [HistoryItem] {
        _items.filter(\.isFavorite)
    }
    
    var passwordItems: [HistoryItem] {
        _items.filter(\.isPassword)
    }
    
    var maxItems: Observable<Int> {
        _maxItems.asObservable()
    }
    
    enum Change {
        case initial
        case insert(index: Int)
        case delete(deletedItem: HistoryItem)
        case clear
        case move(from: Int, to: Int)
        case itemLimitDecreased(deletedItems: [HistoryItem])
        case favoriteChanged(item: HistoryItem, isFavorite: Bool)
        case passwordChanged(item: HistoryItem, isPassword: Bool)
        case pinnedLimitExceeded(current: Int, max: Int)
    }
    
    typealias SubscribeHandler = ([HistoryItem], Change) -> Void
    private var subscriptions = [Subscription]()
    
    private let bundleIdDenylist: Set<String> = [
        "com.agilebits.onepassword7",
        "com.agilebits.onepassword4",
        "com.agilebits.onepassword-osx-helper",
        "com.1password.1password",
        "com.1password.1password-launcher",
        "com.lastpass.LastPass",
        "com.bitwarden.desktop",
        "com.dashlane.dashlanephonefinal",
        "com.keeperpasswordmanager.osx",
        "com.elpassapp.Elpass",
        "com.apple.keychainaccess",
        "com.apple.Passwords",
        "com.protonmail.pass",
        "com.nordpass.macos",
        "com.enpass.desktop",
    ]
    
    private let pasteboardTypeDenylist: Set = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
        "net.antelle.keeweb",
        "com.lastpass.lastpasspasteboardtype",
        "com.bitwarden.desktop.copied-from-bitwarden",
    ]
    
    private let pasteboardTypeIgnoreList = Set([
        "dyn.ah62d4rv4gu8zg55zsmv0nvperf4g86varvu0635zqfx0nkdsqf00nkduqf31k3pcr7u1e3basv61a3k",
    ].map({ NSPasteboard.PasteboardType(rawValue: $0) }))
    
    private static let deduplicationLookback = 20
    
    init(historyFM: HistoryFileManager = .default, cache: HistoryCache, items: [HistoryItem], maxItems: Int = Constants.system.maxHistoryItems) {
        self.historyFM = historyFM
        self.cache = cache
        self._items = items
        self._maxItems = BehaviorRelay<Int>(value: maxItems)
        
        if items.count > maxItems {
            reduceHistory(to: maxItems)
        }
    }
    
    static func load(historyFM: HistoryFileManager = .default, cache: HistoryCache) -> History {
        return historyFM.loadHistory(cache: cache)
    }
    
    @discardableResult
    func subscribe(onNext: @escaping SubscribeHandler) -> () -> Void {
        let subscription = Subscription(handler: onNext)
        subscriptions.append(subscription)
        onNext(_items, Change.initial)
        return { [weak self, weak subscription] in
            guard let self, let subscription else { return }
            self.subscriptions.removeAll { $0 === subscription }
        }
    }
    
    private func notify(_ change: Change) {
        subscriptions.forEach { $0.handler(_items, change) }
    }
    
    func insertItem(_ item: HistoryItem, at i: Int) {
        _items.insert(item, at: i)
        notify(Change.insert(index: i))
        historyFM.insertItem(item, historyOrder: _items)
        pruneExcessItems()
    }
    
    func deleteItem(at i: Int) {
        let removed = _items.remove(at: i)
        notify(Change.delete(deletedItem: removed))
        historyFM.deleteItem(newHistory: _items, deleted: removed)
    }
    
    func deleteItem(withId id: UUID) {
        guard let index = index(ofId: id) else { return }
        deleteItem(at: index)
    }
    
    func index(of item: HistoryItem) -> Int? {
        index(ofId: item.fsId)
    }
    
    func index(ofId id: UUID) -> Int? {
        _items.firstIndex(where: { $0.fsId == id })
    }
    
    func clear(nonFavoritesOnly: Bool = false) {
        if nonFavoritesOnly {
            let removed = _items.filter { !$0.isPinnedFromPruning }
            guard !removed.isEmpty else { return }
            _items = _items.filter(\.isPinnedFromPruning)
            removed.forEach { $0.stopCaching() }
            historyFM.deleteItems(removed, historyOrder: _items)
            notify(Change.clear)
            return
        }
        _items.forEach({ $0.stopCaching() })
        _items = []
        notify(Change.clear)
        historyFM.clearHistory()
    }
    
    func setFavorite(_ isFavorite: Bool, for item: HistoryItem) {
        guard let index = index(of: item) else { return }
        guard _items[index].isFavorite != isFavorite else { return }
        _items[index].isFavorite = isFavorite
        historyFM.setFavorite(isFavorite, for: item)
        notify(Change.favoriteChanged(item: item, isFavorite: isFavorite))
    }
    
    @discardableResult
    func toggleFavorite(for item: HistoryItem) -> Bool {
        guard let index = index(of: item) else { return item.isFavorite }
        let newValue = !_items[index].isFavorite
        setFavorite(newValue, for: item)
        return newValue
    }
    
    func setPassword(_ isPassword: Bool, for item: HistoryItem, comment: String? = nil) {
        guard let index = index(of: item) else { return }
        let resolvedComment = comment ?? (isPassword ? _items[index].passwordComment : "")
        let passwordChanged = _items[index].isPassword != isPassword
        let commentChanged = _items[index].passwordComment != resolvedComment
        guard passwordChanged || commentChanged else { return }
        _items[index].isPassword = isPassword
        _items[index].passwordComment = isPassword ? resolvedComment : ""
        if isPassword {
            item.stopCaching()
        }
        historyFM.setPassword(isPassword, comment: _items[index].passwordComment, for: item)
        notify(Change.passwordChanged(item: item, isPassword: isPassword))
    }
    
    func setPasswordComment(_ comment: String, for item: HistoryItem) {
        guard let index = index(of: item), _items[index].isPassword else { return }
        let trimmed = comment.trimmingCharacters(in: .whitespacesAndNewlines)
        guard _items[index].passwordComment != trimmed else { return }
        _items[index].passwordComment = trimmed
        historyFM.setPasswordComment(trimmed, for: item)
        notify(Change.passwordChanged(item: item, isPassword: true))
    }
    
    @discardableResult
    func togglePassword(for item: HistoryItem) -> Bool {
        guard let index = index(of: item) else { return item.isPassword }
        let newValue = !_items[index].isPassword
        setPassword(newValue, for: item)
        return newValue
    }
    
    func moveItem(at i: Int, to j: Int) {
        let item = _items.remove(at: i)
        _items.insert(item, at: j)
        notify(Change.move(from: i, to: j))
        historyFM.moveItem(newHistory: _items, from: i, to: j)
    }
    
    func moveItem(_ item: HistoryItem, to destination: HistoryItem) {
        guard let from = index(of: item), let to = index(of: destination), from != to else { return }
        moveItem(at: from, to: to)
    }
    
    private func pruneExcessItems() {
        var deleted: [HistoryItem] = []
        while _items.count > _maxItems.value {
            guard let index = _items.lastIndex(where: { !$0.isPinnedFromPruning }) else {
                notify(Change.pinnedLimitExceeded(current: _items.count, max: _maxItems.value))
                break
            }
            deleted.append(_items.remove(at: index))
        }
        guard !deleted.isEmpty else { return }
        historyFM.deleteItems(deleted, historyOrder: _items)
        for item in deleted {
            notify(Change.delete(deletedItem: item))
        }
    }
    
    func recordPasteboardChange(withCount changeCount: Int) {
        _lastRecordedChangeCount.accept(changeCount)
    }
    
    func setMaxItems(_ maxItems: Int) {
        if maxItems < _maxItems.value {
            reduceHistory(to: maxItems)
        }
        _maxItems.accept(maxItems)
    }
    
    private func reduceHistory(to maxItems: Int) {
        guard _items.count > maxItems else { return }
        var deletedItems: [HistoryItem] = []
        while _items.count > maxItems {
            guard let index = _items.lastIndex(where: { !$0.isPinnedFromPruning }) else {
                notify(Change.pinnedLimitExceeded(current: _items.count, max: maxItems))
                break
            }
            deletedItems.append(_items.remove(at: index))
        }
        guard !deletedItems.isEmpty else { return }
        historyFM.deleteItems(deletedItems, historyOrder: _items)
        notify(Change.itemLimitDecreased(deletedItems: deletedItems))
    }
    
    private func isDuplicatePayload(
        _ payload: [NSPasteboard.PasteboardType: Data],
        comparedTo items: [HistoryItem]
    ) -> Bool {
        for item in items.prefix(Self.deduplicationLookback) {
            var matches = true
            for (type, bytes) in payload {
                guard let previous = item.data(forType: type), previous == bytes else {
                    matches = false
                    break
                }
            }
            if matches { return true }
        }
        return false
    }
    
    private static func extractPasteboardPayload(
        from item: NSPasteboardItem,
        filteredTypes: Set<NSPasteboard.PasteboardType>,
        comparedTo recentItems: [HistoryItem]
    ) -> [NSPasteboard.PasteboardType: Data] {
        var data = [NSPasteboard.PasteboardType: Data]()
        for type in filteredTypes {
            guard let payload = item.data(forType: type) else {
                #if DEBUG
                print("Warning: new pasteboard data nil for type '\(type.rawValue)'")
                #endif
                continue
            }
            data[type] = payload
        }
        return data
    }
}

extension History: PasteboardMonitorDelegate {
    
    func pasteboardDidChange(_ pasteboard: NSPasteboard, originBundleId: String?) {
        if pasteboard.changeCount == lastRecordedChangeCount {
            return
        }
        
        let liveBundleId = NSWorkspace.shared.frontmostApplication?.bundleIdentifier ?? originBundleId
        if let bundleId = liveBundleId, bundleIdDenylist.contains(bundleId) {
            recordPasteboardChange(withCount: pasteboard.changeCount)
            return
        }
        
        guard let pasteboardItems = pasteboard.pasteboardItems else {
            recordPasteboardChange(withCount: pasteboard.changeCount)
            return
        }
        
        for item in pasteboardItems.reversed() {
            let filteredTypes = Set(item.types).subtracting(self.pasteboardTypeIgnoreList)
            let hasTypes = !filteredTypes.isEmpty
            let hasNoDeniedTypes = Set(filteredTypes.map({ $0.rawValue })).isDisjoint(with: pasteboardTypeDenylist)
            
            if hasTypes && hasNoDeniedTypes {
                var data = Self.extractPasteboardPayload(
                    from: item,
                    filteredTypes: filteredTypes,
                    comparedTo: self._items
                )
                if data.isEmpty, let raster = HistoryItem.extractRasterData(from: item) {
                    data = raster
                }
                if !data.isEmpty, !isDuplicatePayload(data, comparedTo: _items) {
                    let historyItem = HistoryItem(unsavedData: data, cache: cache, sourceBundleId: liveBundleId)
                    insertItem(historyItem, at: 0)
                }
            }
        }
        
        recordPasteboardChange(withCount: pasteboard.changeCount)
    }
}
