//
// HistoryPasteboardPolicy — denylist rules for password managers and concealed pasteboard types.
//
// Copyright (C) 2026 Aleksey Karakuts <aleksey@karakuts.com>
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
import Cocoa

enum HistoryPasteboardPolicy {

  static let bundleIdDenylist: Set<String> = [
    "com.agilebits.onepassword7",
    "com.agilebits.onepassword4",
    "com.agilebits.onepassword-osx-helper",
    "com.1password.1password",
    "com.1password.1password-launcher",
    "com.lastpass.LastPass",
    "com.bitwarden.desktop",
    "com.dashlane.dashlanephonefinal",
    "com.keeperpasswordmanager.osx",
    "com.elpassapp.Elpass",
    "com.apple.keychainaccess",
    "com.apple.Passwords",
    "com.protonmail.pass",
    "com.nordpass.macos",
    "com.enpass.desktop",
  ]

  static let pasteboardTypeDenylist: Set<String> = [
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "com.typeit4me.clipping",
    "de.petermaurer.TransientPasteboardType",
    "Pasteboard generator type",
    "net.antelle.keeweb",
    "com.lastpass.lastpasspasteboardtype",
    "com.bitwarden.desktop.copied-from-bitwarden",
  ]

  static let pasteboardTypeIgnoreList: Set<NSPasteboard.PasteboardType> = Set([
    "dyn.ah62d4rv4gu8zg55zsmv0nvperf4g86varvu0635zqfx0nkdsqf00nkduqf31k3pcr7u1e3basv61a3k",
  ].map { NSPasteboard.PasteboardType(rawValue: $0) })

  static func shouldIgnoreSource(bundleId: String?) -> Bool {
    guard let bundleId else { return false }
    return bundleIdDenylist.contains(bundleId)
  }

  /// Drops ignored metadata types and password-manager markers; keeps safe payload types.
  static func usableTypes(from types: Set<NSPasteboard.PasteboardType>) -> Set<NSPasteboard.PasteboardType> {
    let raw = Set(types.map(\.rawValue))
    let securityMarkers: Set<String> = [
      "org.nspasteboard.ConcealedType",
      "org.nspasteboard.TransientType",
      "org.nspasteboard.AutoGeneratedType",
    ]
    if !raw.isDisjoint(with: securityMarkers) {
      return []
    }
    return types
      .subtracting(pasteboardTypeIgnoreList)
      .filter { !pasteboardTypeDenylist.contains($0.rawValue) }
  }
}
