//
//  History.swift
//  VaultClip
//
//  Copyright (C) 2019 Matthew Davidson
//  Copyright (C) 2026 Aleksey Karakuts <aleksey@karakuts.com>
//
//  SPDX-License-Identifier: GPL-3.0-or-later
//
import Foundation
import Cocoa
import RxSwift
import RxRelay

/// Representation of all the history
class History {
    
    private var _items = [HistoryItem]()
    
    private var _lastRecordedChangeCount = BehaviorRelay<Int>(value: -1)
    
    var observableLastRecordedChangeCount: Observable<Int> {
        return _lastRecordedChangeCount.asObservable()
    }
    
    var lastRecordedChangeCount: Int {
        return _lastRecordedChangeCount.value
    }
    
    var historyFM: HistoryFileManager
    var cache: HistoryCache
    
    private var _maxItems: BehaviorRelay<Int>
    
    private final class Subscription {
        let handler: SubscribeHandler
        init(handler: @escaping SubscribeHandler) { self.handler = handler }
    }
    
    var items: [HistoryItem] {
        get { self._items }
    }
    
    var favoriteItems: [HistoryItem] {
        _items.filter(\.isFavorite)
    }
    
    var passwordItems: [HistoryItem] {
        _items.filter(\.isPassword)
    }
    
    var maxItems: Observable<Int> {
        _maxItems.asObservable()
    }
    
    enum Change {
        case initial
        case insert(index: Int)
        case delete(deletedItem: HistoryItem)
        case clear
        case move(from: Int, to: Int)
        case itemLimitDecreased(deletedItems: [HistoryItem])
        case favoriteChanged(item: HistoryItem, isFavorite: Bool)
        case passwordChanged(item: HistoryItem, isPassword: Bool)
        case pinnedLimitExceeded(current: Int, max: Int)
    }
    
    typealias SubscribeHandler = ([HistoryItem], Change) -> Void
    private var subscriptions = [Subscription]()
    
    private let bundleIdDenylist: Set<String> = [
        "com.agilebits.onepassword7",
        "com.agilebits.onepassword4",
        "com.agilebits.onepassword-osx-helper",
        "com.1password.1password",
        "com.1password.1password-launcher",
        "com.lastpass.LastPass",
        "com.bitwarden.desktop",
        "com.dashlane.dashlanephonefinal",
        "com.keeperpasswordmanager.osx",
        "com.elpassapp.Elpass",
        "com.apple.keychainaccess",
        "com.apple.Passwords",
        "com.protonmail.pass",
        "com.nordpass.macos",
        "com.enpass.desktop",
    ]
    
    private let pasteboardTypeDenylist: Set = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
        "net.antelle.keeweb",
        "com.lastpass.lastpasspasteboardtype",
        "com.bitwarden.desktop.copied-from-bitwarden",
    ]
    
    private let pasteboardTypeIgnoreList = Set([
        "dyn.ah62d4rv4gu8zg55zsmv0nvperf4g86varvu0635zqfx0nkdsqf00nkduqf31k3pcr7u1e3basv61a3k",
    ].map({ NSPasteboard.PasteboardType(rawValue: $0) }))
    
    private static let deduplicationLookback = 20
    
    init(historyFM: HistoryFileManager = .default, cache: HistoryCache, items: [HistoryItem], maxItems: Int = Constants.system.maxHistoryItems) {
        self.historyFM = historyFM
        self.cache = cache
        self._items = items
        self._maxItems = BehaviorRelay<Int>(value: maxItems)
        
        if items.count > maxItems {
            reduceHistory(to: maxItems)
        }
    }
    
    static func load(historyFM: HistoryFileManager = .default, cache: HistoryCache) -> History {
        return historyFM.loadHistory(cache: cache)
    }
    
    @discardableResult
    func subscribe(onNext: @escaping SubscribeHandler) -> () -> Void {
        let subscription = Subscription(handler: onNext)
        subscriptions.append(subscription)
        onNext(_items, Change.initial)
        return { [weak self, weak subscription] in
            guard let self, let subscription else { return }
            self.subscriptions.removeAll { $0 === subscription }
        }
    }
    
    private func notify(_ change: Change) {
        subscriptions.forEach { $0.handler(_items, change) }
    }
    
    func insertItem(_ item: HistoryItem, at i: Int) {
        _items.insert(item, at: i)
        notify(Change.insert(index: i))
        historyFM.insertItem(item, historyOrder: _items)
        pruneExcessItems()
    }
    
    func deleteItem(at i: Int) {
        let removed = _items.remove(at: i)
        notify(Change.delete(deletedItem: removed))
        historyFM.deleteItem(newHistory: _items, deleted: removed)
    }
    
    func deleteItem(withId id: UUID) {
        guard let index = index(ofId: id) else { return }
        deleteItem(at: index)
    }
    
    func index(of item: HistoryItem) -> Int? {
        index(ofId: item.fsId)
    }
    
    func index(ofId id: UUID) -> Int? {
        _items.firstIndex(where: { $0.fsId == id })
    }
    
    func clear(nonFavoritesOnly: Bool = false) {
        if nonFavoritesOnly {
            let removed = _items.filter { !$0.isPinnedFromPruning }
            guard !removed.isEmpty else { return }
            _items = _items.filter(\.isPinnedFromPruning)
            removed.forEach { $0.stopCaching() }
            historyFM.deleteItems(removed, historyOrder: _items)
            notify(Change.clear)
            return
        }
        _items.forEach({ $0.stopCaching() })
        _items = []
        notify(Change.clear)
        historyFM.clearHistory()
    }
    
    func setFavorite(_ isFavorite: Bool, for item: HistoryItem) {
        guard let index = index(of: item) else { return }
        guard _items[index].isFavorite != isFavorite else { return }
        _items[index].isFavorite = isFavorite
        historyFM.setFavorite(isFavorite, for: item)
        notify(Change.favoriteChanged(item: item, isFavorite: isFavorite))
    }
    
    @discardableResult
    func toggleFavorite(for item: HistoryItem) -> Bool {
        guard let index = index(of: item) else { return item.isFavorite }
        let newValue = !_items[index].isFavorite
        setFavorite(newValue, for: item)
        return newValue
    }
    
    func setPassword(
        _ isPassword: Bool,
        for item: HistoryItem,
        comment: String? = nil,
        login: String? = nil
    ) {
        guard let index = index(of: item) else { return }
        let resolvedComment = (comment ?? (isPassword ? _items[index].passwordComment : ""))
            .trimmingCharacters(in: .whitespacesAndNewlines)
        let resolvedLogin = (login ?? (isPassword ? _items[index].passwordLogin : ""))
            .trimmingCharacters(in: .whitespacesAndNewlines)
        let passwordChanged = _items[index].isPassword != isPassword
        let commentChanged = _items[index].passwordComment != resolvedComment
        let loginChanged = _items[index].passwordLogin != resolvedLogin
        guard passwordChanged || commentChanged || loginChanged else { return }
        _items[index].isPassword = isPassword
        _items[index].passwordComment = isPassword ? resolvedComment : ""
        _items[index].passwordLogin = isPassword ? resolvedLogin : ""
        if isPassword {
            item.stopCaching()
        }
        historyFM.setPassword(
            isPassword,
            comment: _items[index].passwordComment,
            login: _items[index].passwordLogin,
            for: item
        )
        notify(Change.passwordChanged(item: item, isPassword: isPassword))
    }
    
    func setPasswordMetadata(comment: String, login: String, for item: HistoryItem) {
        guard let index = index(of: item), _items[index].isPassword else { return }
        let trimmedComment = comment.trimmingCharacters(in: .whitespacesAndNewlines)
        let trimmedLogin = login.trimmingCharacters(in: .whitespacesAndNewlines)
        guard _items[index].passwordComment != trimmedComment || _items[index].passwordLogin != trimmedLogin else { return }
        _items[index].passwordComment = trimmedComment
        _items[index].passwordLogin = trimmedLogin
        historyFM.setPasswordMetadata(comment: trimmedComment, login: trimmedLogin, for: item)
        notify(Change.passwordChanged(item: item, isPassword: true))
    }
    
    @discardableResult
    func togglePassword(for item: HistoryItem) -> Bool {
        guard let index = index(of: item) else { return item.isPassword }
        let newValue = !_items[index].isPassword
        setPassword(newValue, for: item)
        return newValue
    }
    
    func moveItem(at i: Int, to j: Int) {
        let item = _items.remove(at: i)
        _items.insert(item, at: j)
        notify(Change.move(from: i, to: j))
        historyFM.moveItem(newHistory: _items, from: i, to: j)
    }
    
    func moveItem(_ item: HistoryItem, to destination: HistoryItem) {
        guard let from = index(of: item), let to = index(of: destination), from != to else { return }
        moveItem(at: from, to: to)
    }
    
    private func pruneExcessItems() {
        var deleted: [HistoryItem] = []
        while _items.count > _maxItems.value {
            guard let index = _items.lastIndex(where: { !$0.isPinnedFromPruning }) else {
                notify(Change.pinnedLimitExceeded(current: _items.count, max: _maxItems.value))
                break
            }
            deleted.append(_items.remove(at: index))
        }
        guard !deleted.isEmpty else { return }
        historyFM.deleteItems(deleted, historyOrder: _items)
        for item in deleted {
            notify(Change.delete(deletedItem: item))
        }
    }
    
    func recordPasteboardChange(withCount changeCount: Int) {
        _lastRecordedChangeCount.accept(changeCount)
    }
    
    func setMaxItems(_ maxItems: Int) {
        if maxItems < _maxItems.value {
            reduceHistory(to: maxItems)
        }
        _maxItems.accept(maxItems)
    }
    
    private func reduceHistory(to maxItems: Int) {
        guard _items.count > maxItems else { return }
        var deletedItems: [HistoryItem] = []
        while _items.count > maxItems {
            guard let index = _items.lastIndex(where: { !$0.isPinnedFromPruning }) else {
                notify(Change.pinnedLimitExceeded(current: _items.count, max: maxItems))
                break
            }
            deletedItems.append(_items.remove(at: index))
        }
        guard !deletedItems.isEmpty else { return }
        historyFM.deleteItems(deletedItems, historyOrder: _items)
        notify(Change.itemLimitDecreased(deletedItems: deletedItems))
    }
    
    private func isDuplicatePayload(
        _ payload: [NSPasteboard.PasteboardType: Data],
        comparedTo items: [HistoryItem]
    ) -> Bool {
        for item in items.prefix(Self.deduplicationLookback) {
            var matches = true
            for (type, bytes) in payload {
                guard let previous = item.data(forType: type), previous == bytes else {
                    matches = false
                    break
                }
            }
            if matches { return true }
        }
        return false
    }
    
    private static func extractPasteboardPayload(
        from item: NSPasteboardItem,
        filteredTypes: Set<NSPasteboard.PasteboardType>,
        comparedTo recentItems: [HistoryItem]
    ) -> [NSPasteboard.PasteboardType: Data] {
        var data = [NSPasteboard.PasteboardType: Data]()
        for type in filteredTypes {
            guard let payload = item.data(forType: type) else {
                #if DEBUG
                print("Warning: new pasteboard data nil for type '\(type.rawValue)'")
                #endif
                continue
            }
            data[type] = payload
        }
        return data
    }
}

extension History: PasteboardMonitorDelegate {

    /// Re-reads the live pasteboard on launch even when `changeCount` matches persisted settings.
    func syncWithPasteboardOnLaunch(_ pasteboard: NSPasteboard) {
        processPasteboardChange(
            pasteboard,
            originBundleId: NSWorkspace.shared.frontmostApplication?.bundleIdentifier,
            ignoreChangeCount: true
        )
    }

    func pasteboardDidChange(_ pasteboard: NSPasteboard, originBundleId: String?) {
        processPasteboardChange(pasteboard, originBundleId: originBundleId, ignoreChangeCount: false)
    }

    private func processPasteboardChange(
        _ pasteboard: NSPasteboard,
        originBundleId: String?,
        ignoreChangeCount: Bool
    ) {
        if !ignoreChangeCount, pasteboard.changeCount == lastRecordedChangeCount {
            return
        }

        let liveBundleId = Self.clipboardSourceBundleId(originBundleId: originBundleId)
        if let bundleId = liveBundleId, bundleIdDenylist.contains(bundleId) {
            PasteboardDiagnostics.log("skipped bundle denylist: \(bundleId)")
            recordPasteboardChange(withCount: pasteboard.changeCount)
            return
        }

        let pasteboardItems = Self.pasteboardItems(from: pasteboard)
        guard !pasteboardItems.isEmpty else {
            PasteboardDiagnostics.log("no pasteboard items (changeCount=\(pasteboard.changeCount))")
            recordPasteboardChange(withCount: pasteboard.changeCount)
            return
        }

        var inserted = 0
        for item in pasteboardItems.reversed() {
            let filteredTypes = Self.usablePasteboardTypes(
                from: Set(item.types),
                ignoreList: pasteboardTypeIgnoreList,
                denylist: pasteboardTypeDenylist
            )
            guard !filteredTypes.isEmpty else { continue }

            var data = Self.extractPasteboardPayload(
                from: item,
                filteredTypes: filteredTypes,
                comparedTo: self._items
            )
            if data.isEmpty, let raster = HistoryItem.extractRasterData(from: item) {
                data = raster
            }
            guard !data.isEmpty else {
                PasteboardDiagnostics.log("empty payload for types: \(filteredTypes.map(\.rawValue))")
                continue
            }
            if isDuplicatePayload(data, comparedTo: _items) {
                PasteboardDiagnostics.log("duplicate payload (\(data.count) types)")
                continue
            }
            let historyItem = HistoryItem(unsavedData: data, cache: cache, sourceBundleId: liveBundleId)
            insertItem(historyItem, at: 0)
            inserted += 1
        }

        PasteboardDiagnostics.log(
            "processed changeCount=\(pasteboard.changeCount) inserted=\(inserted) historyCount=\(_items.count) launchSync=\(ignoreChangeCount)"
        )
        recordPasteboardChange(withCount: pasteboard.changeCount)
    }

    private static func clipboardSourceBundleId(originBundleId: String?) -> String? {
        let ownBundleId = Constants.branding.bundleIdentifier
        let frontmost = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        if frontmost == ownBundleId {
            return originBundleId
        }
        return frontmost ?? originBundleId
    }

    /// Drops ignored metadata types and password-manager markers; keeps safe payload types.
    private static func usablePasteboardTypes(
        from types: Set<NSPasteboard.PasteboardType>,
        ignoreList: Set<NSPasteboard.PasteboardType>,
        denylist: Set<String>
    ) -> Set<NSPasteboard.PasteboardType> {
        let raw = Set(types.map(\.rawValue))
        let securityMarkers: Set<String> = [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
        ]
        if !raw.isDisjoint(with: securityMarkers) {
            return []
        }
        return types
            .subtracting(ignoreList)
            .filter { !denylist.contains($0.rawValue) }
    }

    /// `pasteboardItems` can be nil while legacy `data(forType:)` still works on some macOS builds.
    private static func pasteboardItems(from pasteboard: NSPasteboard) -> [NSPasteboardItem] {
        if let items = pasteboard.pasteboardItems, !items.isEmpty {
            return items
        }
        guard let types = pasteboard.types, !types.isEmpty else { return [] }
        let item = NSPasteboardItem()
        var wroteAny = false
        for type in types {
            if let data = pasteboard.data(forType: type) {
                item.setData(data, forType: type)
                wroteAny = true
            } else if let string = pasteboard.string(forType: type),
                      let data = string.data(using: .utf8) {
                item.setData(data, forType: type)
                wroteAny = true
            }
        }
        return wroteAny ? [item] : []
    }
}
